[tool.poetry]
name = "ubar"
version = "0.1.0"
description = ""
authors = ["ohinibla <ohinibla@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.2"
phonenumbers = "^9.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
